import { mkdirSync, readFileSync } from "fs";
import { describe, expect, it } from "vitest";
import {
  categorize,
  formatDiffBlock,
  noiseReason,
  parseIgnorePaths,
  patchFileName,
  readManifest,
  writeDiff,
} from "../github/script/review-diff";

describe("Bonk precomputed diff", () => {
  it("parses ignore_paths strictly and never covers workflows", () => {
    const { rules, warnings } = parseIgnorePaths(
      [
        "docs/generated/",
        "src/**/*.snap",
        "types/generated-snapshot/*.d.ts",
        "/abs/path",
        "../escape",
        "src/[ab].ts",
        "!keep.ts",
        "foo**/bar",
        "**/*.yml",
        ".github/",
        ".github/workflows/*.md",
        ".*/work*/x",
        ".github/CODEOWNERS",
        "src/**/*.c++",
      ].join("\n"),
    );
    expect(rules.map((rule) => rule.pattern)).toEqual([
      "docs/generated/",
      "src/**/*.snap",
      "types/generated-snapshot/*.d.ts",
      ".github/CODEOWNERS",
      "src/**/*.c++",
    ]);
    expect(warnings).toHaveLength(9);
    const matches = (path: string) => rules.some((rule) => rule.regex.test(path));
    expect(matches("docs/generated/a/b.md")).toBe(true);
    expect(matches("docs/generated")).toBe(false);
    expect(matches("src/a/b/c.snap")).toBe(true);
    expect(matches("src/c.snap")).toBe(true);
    expect(matches("types/generated-snapshot/a/b.d.ts")).toBe(false);
    expect(matches("types/generated-snapshot/b.d.ts")).toBe(true);
    expect(matches(".github/workflows/ci.yml")).toBe(false);
    // `+` is literal, as in C++ file names.
    expect(matches("src/workerd/api/url.c++")).toBe(true);
    expect(matches("src/workerd/api/url.cc")).toBe(false);
    // Bad input warns but never throws.
    expect(parseIgnorePaths(undefined)).toEqual({ rules: [], warnings: [] });
  });

  it("filters noise but never migrations", () => {
    expect(noiseReason("pnpm-lock.yaml")).toBe("lockfile");
    expect(noiseReason("third_party/zlib/zlib.h")).toBe("vendored");
    expect(noiseReason("web/app.min.js")).toBe("minified");
    expect(noiseReason("web/dist/app.js")).toBe("bundled");
    expect(noiseReason("web/app.js.map")).toBe("source map");
    expect(
      noiseReason(
        "src/api.pb.h",
        "@@ -0,0 +1,2 @@\n+// Code generated by protoc. DO NOT EDIT.\n+x",
      ),
    ).toBe("generated");
    expect(noiseReason("db/migrations/0001.sql", "@@ -0,0 +1 @@\n+-- @generated")).toBeNull();
    expect(noiseReason("src/workerd/api/url.c++", "@@ -1 +1 @@\n-a\n+b")).toBeNull();
    expect(categorize("src/workerd/api/tests/url-test.js")).toBe("tests");
    expect(categorize("docs/reference/api.md")).toBe("docs");
    expect(categorize("src/workerd/api/BUILD.bazel")).toBe("build");
    expect(categorize(".github/workflows/ci.yml")).toBe("config");
    expect(categorize("src/workerd/api/url.c++")).toBe("code");
  });

  it("keeps patch file names unique and bounded", () => {
    expect(patchFileName("src/a b/c.ts")).toBe("src_a_b_c.ts.patch");
    const long = `${"deep/".repeat(40)}file.ts`;
    const name = patchFileName(long);
    expect(name.length).toBeLessThanOrEqual(120);
    expect(name).not.toBe(patchFileName(`${"deep/".repeat(41)}file.ts`));
  });

  it("writes patches and a manifest and inlines them within the budget", () => {
    const dir = `/tmp/bonk-test/diff-${crypto.randomUUID()}`;
    mkdirSync(dir, { recursive: true });
    const manifest = writeDiff(
      dir,
      [
        {
          filename: "src/a.ts",
          status: "modified",
          additions: 1,
          deletions: 1,
          patch: "@@ -1 +1 @@\n-a\n+b",
        },
        {
          filename: "yarn.lock",
          status: "modified",
          additions: 5,
          deletions: 5,
          patch: "@@ -1 +1 @@\n-x\n+y",
        },
        { filename: "logo.png", status: "added", additions: 0, deletions: 0 },
        {
          filename: "docs/skip.md",
          status: "added",
          additions: 1,
          deletions: 0,
          patch: "@@ -0,0 +1 @@\n+x",
        },
      ],
      parseIgnorePaths("docs/").rules,
      false,
    );
    expect(readManifest(dir)).toEqual(manifest);
    const [code, lock, image, doc] = manifest.files;
    expect(readFileSync(code.patchFile!, "utf8")).toBe("@@ -1 +1 @@\n-a\n+b\n");
    expect(lock).toMatchObject({ filtered: "lockfile", patchFile: null });
    expect(image).toMatchObject({ filtered: null, patchFile: null });
    expect(doc).toMatchObject({ filtered: "ignore_paths: docs/", patchFile: null });

    const inline = formatDiffBlock(manifest);
    expect(inline).toContain("- modified src/a.ts +1/-1 [code]\n");
    expect(inline).toContain("=== src/a.ts ===\n@@ -1 +1 @@\n-a\n+b");
    expect(inline).toContain(
      "logo.png +0/-0 [code] (no patch from GitHub: binary or too large; read the file)",
    );
    expect(inline).toContain(
      "not reviewed (filtered):\n- yarn.lock (lockfile)\n- docs/skip.md (ignore_paths: docs/)",
    );

    const listed = formatDiffBlock(manifest, 5);
    expect(listed).not.toContain("=== src/a.ts ===");
    expect(listed).toContain(`[code] patch: ${code.patchFile}`);
  });
});
