// Precomputed pull request diff for review runs (opt-in via `rereview_context`).
//
// Preflight writes one patch per changed file, taken from GitHub's pull
// request files API (the diff against the merge base, as GitHub shows it),
// plus a manifest. The prompt carries the patches, specialists read their
// share from the directory, and the publisher places inline comments on the
// same hunks, so every stage sees one diff.

import { createHash } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { core, escapePromptValue } from "./context";
import { fetchWithRetry } from "./http";

export type Category = "code" | "tests" | "docs" | "build" | "config";

export interface DiffFile {
  path: string;
  previousPath?: string;
  status: string;
  additions: number;
  deletions: number;
  // Absolute path of the file's patch, or null when GitHub sent no patch
  // (binary or too large) or the file was filtered.
  patchFile: string | null;
  category: Category;
  // Why the file is not part of the review, or null.
  filtered: string | null;
}

export interface DiffManifest {
  dir: string;
  files: DiffFile[];
  // GitHub lists at most 3000 files per pull request.
  truncated: boolean;
}

export interface PullRequestFile {
  filename: string;
  previous_filename?: string;
  status: string;
  additions: number;
  deletions: number;
  patch?: string;
}

// Inline all patches into the prompt below this many bytes; above it the
// prompt lists the patch files for the model to read.
export const DIFF_PROMPT_BUDGET = 150_000;
const MAX_FILE_PAGES = 30;
const MAX_PATCH_NAME = 120;

const TEST_PATH_PATTERN =
  /(?:^|\/)(?:tests?|__tests__|spec|testdata|fixtures?)\/|[._-](?:test|spec)s?\.[^/]+$|\.wd-test$/i;

export function isTestPath(path: string): boolean {
  return TEST_PATH_PATTERN.test(path);
}

export function categorize(path: string): Category {
  if (isTestPath(path)) return "tests";
  if (/\.(?:md|mdx|rst|adoc|txt)$/i.test(path) || /(?:^|\/)docs?\//i.test(path)) return "docs";
  if (
    /(?:^|\/)(?:BUILD(?:\.bazel)?|WORKSPACE(?:\.bazel)?|MODULE\.bazel|Makefile|CMakeLists\.txt|justfile|Dockerfile|package\.json)$/.test(
      path,
    ) ||
    /\.(?:bzl|cmake|mk)$/.test(path)
  ) {
    return "build";
  }
  if (/\.(?:json|jsonc|ya?ml|toml|ini|cfg|conf)$/i.test(path) || path.startsWith(".github/")) {
    return "config";
  }
  return "code";
}

const LOCKFILES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "Cargo.lock",
  "Gemfile.lock",
  "poetry.lock",
  "Pipfile.lock",
  "uv.lock",
  "go.sum",
  "composer.lock",
  "MODULE.bazel.lock",
  "flake.lock",
]);
const GENERATED_MARKER =
  /^[+ ].{0,120}(?:@generated|DO NOT EDIT|Code generated by|auto-?generated)/im;
const MIGRATION_PATH = /(?:^|\/)migrations?\//i;

// Files that are rarely worth a reviewer's time. Migrations are never
// filtered: they often look generated but are hand-reviewed schema changes.
export function noiseReason(path: string, patch?: string): string | null {
  if (MIGRATION_PATH.test(path)) return null;
  const name = path.split("/").at(-1) ?? path;
  if (LOCKFILES.has(name)) return "lockfile";
  if (/(?:^|\/)(?:vendor|vendored|third_party|third-party|node_modules)\//.test(path)) {
    return "vendored";
  }
  if (/\.min\.(?:js|mjs|cjs|css)$/.test(path)) return "minified";
  if (/(?:^|\/)dist\//.test(path) || /\.bundle\.(?:js|mjs|cjs)$/.test(path)) return "bundled";
  if (/\.(?:js|mjs|cjs|css)\.map$/.test(path)) return "source map";
  if (patch && GENERATED_MARKER.test(patch.split("\n").slice(0, 20).join("\n"))) {
    return "generated";
  }
  return null;
}

export interface IgnoreRule {
  pattern: string;
  regex: RegExp;
}

function segmentRegex(segment: string): string {
  return segment
    .split("*")
    .map((part) => part.replace(/[.+^${}()|[\]\\]/g, "\\$&"))
    .join("[^/]*");
}

function segmentMatches(segment: string, name: string): boolean {
  return segment === "**" || new RegExp(`^${segmentRegex(segment)}$`).test(name);
}

// `ignore_paths` grammar: comma- or newline-separated patterns, each relative
// to the repository root. A pattern matches a whole path; `*` matches within
// one path segment, `**` (a whole segment) matches any number of segments, and
// a trailing `/` matches everything below a directory. No leading `/`, `..`,
// `?`, brackets, or negation. A pattern that could match anything under
// `.github/workflows/` is rejected, so workflow changes are always reviewed.
// Bad patterns are skipped with a warning, never fatal.
export function parseIgnorePaths(input: string | undefined): {
  rules: IgnoreRule[];
  warnings: string[];
} {
  const rules: IgnoreRule[] = [];
  const warnings: string[] = [];
  for (const raw of (input ?? "").split(/[\n,]/)) {
    const pattern = raw.trim();
    if (!pattern) continue;
    const reject = (reason: string) =>
      warnings.push(`Ignoring ignore_paths entry "${pattern}": ${reason}`);
    if (!/^[A-Za-z0-9._\-/*]+$/.test(pattern)) {
      reject("only letters, digits, '.', '_', '-', '/', and '*' are allowed");
      continue;
    }
    const expanded = pattern.endsWith("/") ? `${pattern}**` : pattern;
    const segments = expanded.split("/");
    if (pattern.startsWith("/") || segments.some((segment) => !segment || segment === "..")) {
      reject("must be a relative path without empty or '..' segments");
      continue;
    }
    if (segments.some((segment) => segment.includes("**") && segment !== "**")) {
      reject("'**' must be a whole path segment");
      continue;
    }
    const coversWorkflows =
      segments[0] === "**" ||
      (segmentMatches(segments[0], ".github") &&
        segments.length > 1 &&
        segmentMatches(segments[1], "workflows"));
    if (coversWorkflows) {
      reject("it could match .github/workflows/, which is always reviewed");
      continue;
    }
    const source = segments
      .map((segment, index) =>
        segment === "**"
          ? index === segments.length - 1
            ? ".*"
            : "(?:[^/]+/)*"
          : `${segmentRegex(segment)}${index === segments.length - 1 ? "" : "/"}`,
      )
      .join("");
    rules.push({ pattern, regex: new RegExp(`^${source}$`) });
  }
  return { rules, warnings };
}

// Flattens a path into one file name; long names keep a readable prefix and a
// hash so they stay unique and within file system limits.
export function patchFileName(path: string): string {
  const flat = path.replace(/[^A-Za-z0-9._-]/g, "_");
  if (flat.length + 6 <= MAX_PATCH_NAME) return `${flat}.patch`;
  const hash = createHash("sha256").update(path).digest("hex").slice(0, 16);
  return `${flat.slice(0, MAX_PATCH_NAME - 24)}-${hash}.patch`;
}

export async function fetchPullRequestFiles(
  token: string,
  repository: string,
  prNumber: string,
): Promise<{ files: PullRequestFile[]; truncated: boolean }> {
  const files: PullRequestFile[] = [];
  for (let page = 1; page <= MAX_FILE_PAGES; page += 1) {
    const resp = await fetchWithRetry(
      `https://api.github.com/repos/${repository}/pulls/${prNumber}/files?per_page=100&page=${page}`,
      { headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" } },
      { timeoutMs: 15000 },
    );
    if (!resp.ok) throw new Error(`Listing pull request files returned ${resp.status}`);
    const batch = (await resp.json()) as PullRequestFile[];
    files.push(...batch);
    if (batch.length < 100) return { files, truncated: false };
  }
  return { files, truncated: true };
}

export function writeDiff(
  dir: string,
  files: PullRequestFile[],
  rules: IgnoreRule[],
  truncated: boolean,
): DiffManifest {
  mkdirSync(dir, { recursive: true });
  const used = new Set<string>();
  const manifest: DiffManifest = { dir, truncated, files: [] };
  for (const file of files) {
    const ignored = rules.find((rule) => rule.regex.test(file.filename));
    const filtered = ignored
      ? `ignore_paths: ${ignored.pattern}`
      : noiseReason(file.filename, file.patch);
    let patchFile: string | null = null;
    if (file.patch !== undefined && !filtered) {
      let name = patchFileName(file.filename);
      if (used.has(name)) name = `${used.size}-${name}`;
      used.add(name);
      patchFile = join(dir, name);
      writeFileSync(patchFile, file.patch.endsWith("\n") ? file.patch : `${file.patch}\n`);
    }
    manifest.files.push({
      path: file.filename,
      ...(file.previous_filename ? { previousPath: file.previous_filename } : {}),
      status: file.status,
      additions: file.additions,
      deletions: file.deletions,
      patchFile,
      category: categorize(file.filename),
      filtered,
    });
  }
  writeFileSync(join(dir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  return manifest;
}

export function readManifest(dir: string | undefined): DiffManifest | null {
  if (!dir) return null;
  const path = join(dir, "manifest.json");
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as DiffManifest;
  } catch {
    return null;
  }
}

// Model-visible text may contain anything; only Bonk's own tags need
// neutralizing, so code keeps its angle brackets.
export function neutralizeTags(text: string): string {
  return text.replace(/<(\/?bonk_)/gi, "&lt;$1");
}

export function readPatch(file: DiffFile): string {
  if (!file.patchFile) return "";
  try {
    return readFileSync(file.patchFile, "utf8");
  } catch {
    return "";
  }
}

export function formatDiffBlock(manifest: DiffManifest, budget = DIFF_PROMPT_BUDGET): string {
  const reviewed = manifest.files.filter((file) => !file.filtered);
  const filtered = manifest.files.filter((file) => file.filtered);
  const patches = reviewed.map((file) => ({ file, patch: readPatch(file) }));
  const bytes = patches.reduce((sum, entry) => sum + Buffer.byteLength(entry.patch), 0);
  const inline = bytes <= budget;

  const lines = ["<bonk_diff>"];
  lines.push(`diff_dir: ${escapePromptValue(manifest.dir)}`);
  lines.push(`manifest: ${escapePromptValue(join(manifest.dir, "manifest.json"))}`);
  lines.push(
    `files: ${manifest.files.length} (${reviewed.length} to review, ${filtered.length} filtered)${manifest.truncated ? "; GitHub listed only the first 3000" : ""}`,
  );
  for (const { file } of patches) {
    const renamed = file.previousPath ? ` (from ${escapePromptValue(file.previousPath)})` : "";
    const patch = file.patchFile
      ? inline
        ? ""
        : ` patch: ${escapePromptValue(file.patchFile)}`
      : " (no patch from GitHub: binary or too large; read the file)";
    lines.push(
      `- ${file.status} ${escapePromptValue(file.path)}${renamed} +${file.additions}/-${file.deletions} [${file.category}]${patch}`,
    );
  }
  if (inline) {
    for (const { file, patch } of patches) {
      if (!patch) continue;
      lines.push(`=== ${escapePromptValue(file.path)} ===`);
      lines.push(neutralizeTags(patch.trimEnd()));
    }
  } else {
    lines.push(
      `The patches total ${bytes} bytes, too many to include here; read each file's patch from its path.`,
    );
  }
  if (filtered.length > 0) {
    lines.push("not reviewed (filtered):");
    for (const file of filtered) {
      lines.push(`- ${escapePromptValue(file.path)} (${escapePromptValue(file.filtered ?? "")})`);
    }
  }
  lines.push("</bonk_diff>");
  return lines.join("\n");
}

export async function prepareDiff(
  token: string,
  repository: string,
  prNumber: string,
  dir: string,
  ignorePaths: string | undefined,
): Promise<DiffManifest> {
  const { rules, warnings } = parseIgnorePaths(ignorePaths);
  for (const warning of warnings) core.warning(warning);
  const { files, truncated } = await fetchPullRequestFiles(token, repository, prNumber);
  return writeDiff(dir, files, rules, truncated);
}
